benchmark:
  client:
    count: 30
    max: 30
    step: 5
  transaction:
    count: 10000
    max: 10000
    step: 50000
  execution:
    maxTime: 600
    timeout: 300
    parallel: true
  script:
    name: src/main/resources/scripts/test.sql
  report:
    path: ./reports
    name: report.html

mysql:
  username: user1
  password: qwerty007
  driverName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/load_test